[package]
name = "rust_minify"
version = "0.2.0"
authors = ["to-omer <toomerhs@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "minify rust code"
repository = "https://github.com/to-omer/rust_minify"
documentation = "https://docs.rs/rust_minify"

[dependencies]
rustc-hash = "2.1.3"
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
quote = "1.0.47"
syn = { version = "3.0.6", features = [
    "full",
    "visit",
    "visit-mut",
    "extra-traits",
] }

[dev-dependencies]
indoc = "2.0.7"
test-case = "3.3.1"
