[package]
name = "minify-rust"
version = "0.1.0"
authors = ["to-omer <toomerhs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1", features = ["full", "parsing"] }
# syn = "1"
proc-macro2 = "1"
quote = "1"
once_cell = "1.7"
