name: CI

on:
  push:


jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup `stable`
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: cargo-fmt
      run: cargo fmt --all -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable-x86_64-pc-windows-msvc
          - stable-x86_64-apple-darwin
          - stable-x86_64-unknown-linux-gnu
        include:
          - { toolchain: stable-x86_64-pc-windows-msvc   , os: windows-latest }
          - { toolchain: stable-x86_64-apple-darwin      , os: macos-latest  }
          - { toolchain: stable-x86_64-unknown-linux-gnu , os: ubuntu-latest }

    name: Build (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup `${{ matrix.toolchain }}`
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy

    - name: cargo-clippy
      run: cargo clippy --workspace --lib --tests

    - name: cargo-build
      run: cargo build --workspace --lib --tests

    - name: cargo-test
      run: cargo test --workspace --no-fail-fast
      env:
        RUST_BACKTRACE: full
