name: CI

on:
  push:


jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup `stable-x86_64-unknown-linux-gnu`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
        components: rustfmt

    - name: cargo-fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable-x86_64-pc-windows-msvc
          - stable-x86_64-apple-darwin
          - stable-x86_64-unknown-linux-gnu
        include:
          - { toolchain: stable-x86_64-pc-windows-msvc   , os: windows-latest }
          - { toolchain: stable-x86_64-apple-darwin      , os: macos-latest  }
          - { toolchain: stable-x86_64-unknown-linux-gnu , os: ubuntu-latest }

    name: Build (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup `${{ matrix.toolchain }}`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        default: true
        profile: minimal
        components: clippy

    - name: cargo-clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --lib --tests

    - name: cargo-build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --lib --tests

    - name: cargo-test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --no-fail-fast
      env:
        RUST_BACKTRACE: full
